# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/26e56ccc-2515-4ded-b53d-1131b1d75770";
      fsType = "btrfs";
      options = [ "subvol=@" "autodefrag" "commit=120" "discard=async" "ssd" "noatime" "compress=zstd:1" "space_cache=v2" ];
    };

  boot.initrd.luks.devices."luks-a4551de6-67de-433d-94f1-7bde6f6ee702".device = "/dev/disk/by-uuid/a4551de6-67de-433d-94f1-7bde6f6ee702";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0D2B-651B";
      fsType = "vfat";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/27afdbb9-adfd-40d4-a03f-b9bb49311a6f";
      fsType = "btrfs";
      options = [ "noatime" "autodefrag" "discard=async" "ssd" "compress=zstd:1" "space_cache=v2" ];
    };

  fileSystems."/Stuff" =
    {
      device = "/dev/disk/by-uuid/e6cc4b28-e7b4-4691-a673-f9281f7d8b9d";
      fsType = "ext4";
      options = [ "rw" "relatime" "noatime" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
